### ISSUE TITLE
Add doctor vacancy location semporna

### ISSUE THREAD

**Issue by paragasu** [phisoft/permaipolyclinics-web#101]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/27353/113951808-e7dbb380-9846-11eb-99d0-f44f5f3a1435.png">

**Comment by qoszira15** [comment]
![Screenshot_2021-04-08_11-20-21](https://user-images.githubusercontent.com/59812971/113963574-70188380-985c-11eb-870e-ce7988b09f33.png)
