### ISSUE TITLE
Create banner

### ISSUE THREAD

**Issue by paragasu** [phisoft/permaipolyclinics-web#21]
Create 3 banner suitable for permai polyclinics

**Comment by Clairefrancis95** [comment]
![1](https://user-images.githubusercontent.com/48192938/55315361-c1881e00-549e-11e9-9b00-20f3a498bcdb.png)
![2](https://user-images.githubusercontent.com/48192938/55315362-c220b480-549e-11e9-8bd3-4cbacca158e7.png)
![3](https://user-images.githubusercontent.com/48192938/55315363-c2b94b00-549e-11e9-82d5-5e3fcebf5a4a.png)

**Comment by paragasu** [comment]
@kennethrick96 Try update this banner to permai website and show claire how it look like.

**Comment by Clairefrancis95** [comment]
![Dentallink brochure](https://user-images.githubusercontent.com/48192938/55450947-805d4e80-5603-11e9-8ae8-d5799baca4cf.jpg)

**Comment by Clairefrancis95** [comment]
![573807-PLOMI9-996](https://user-images.githubusercontent.com/48192938/55537049-e0302400-56ed-11e9-97f8-51c838a82d83.jpg)

**Comment by Clairefrancis95** [comment]
![pp1](https://user-images.githubusercontent.com/48192938/55539163-9b5abc00-56f2-11e9-8124-e5589bf49891.jpg)

**Comment by Clairefrancis95** [comment]
![64](https://user-images.githubusercontent.com/48192938/55539776-11abee00-56f4-11e9-9a24-e7e5e83699b7.jpg)

**Comment by Clairefrancis95** [comment]
![O6UZR60](https://user-images.githubusercontent.com/48192938/55540009-9b5bbb80-56f4-11e9-8e8b-d6a9318eae9c.jpg)

**Comment by Clairefrancis95** [comment]
![pp2](https://user-images.githubusercontent.com/48192938/55540606-e9bd8a00-56f5-11e9-9d9b-ff57bc0cab19.png)

**Comment by Clairefrancis95** [comment]
![pp3](https://user-images.githubusercontent.com/48192938/55606699-6d39b280-57ac-11e9-849e-4fc733c47631.png)
