### ISSUE TITLE
Update covid main banner

### ISSUE THREAD

**Issue by paragasu** [phisoft/permaipolyclinics-web#55]
<img width="1756" alt="image" src="https://user-images.githubusercontent.com/27353/95945484-260a9400-0e1d-11eb-8ed0-8ee7d11a1c55.png">

[BANNER COVID 5X3 2.pdf](https://github.com/phisoft/permaipolyclinics-web/files/5375675/BANNER.COVID.5X3.2.pdf)

Modify a littlbit so the website do not look ugly

**Comment by izahshahirah** [comment]
done
