### ISSUE TITLE
Fix main page broken in mobile

### ISSUE THREAD

**Issue by paragasu** [phisoft/permaipolyclinics-web#77]
<img width="1750" alt="image" src="https://user-images.githubusercontent.com/27353/97847302-611c2b00-1d2a-11eb-9686-c4854d7823ad.png">

**Comment by izahshahirah** [comment]
the main page and others should be fine.

<img width="1792" alt="Screenshot 2020-11-02 at 4 58 43 PM" src="https://user-images.githubusercontent.com/60636305/97848889-b48f7880-1d2c-11eb-9e62-7df3dfea4c79.png">

**Comment by izahshahirah** [comment]
done
