### ISSUE TITLE
Update timing & pricing if different then existing one

### ISSUE THREAD

**Issue by paragasu** [phisoft/permaipolyclinics-web#98]
![image](https://user-images.githubusercontent.com/27353/113947756-f376ac80-983d-11eb-86d9-d485098f0b2a.png)

**Comment by qoszira15** [comment]
![Screenshot_2021-04-08_11-17-08](https://user-images.githubusercontent.com/59812971/113963335-fc767680-985b-11eb-8f26-1f43becd75b1.png)
